services:
  - type: web
    name: my-tg-bot
    env: docker
    plan: free
    buildCommand: ""   # handled by Dockerfile
    startCommand: ""   # handled by Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: "your-telegram-bot-token"
      - key: API_ID
        value: "your-telethon-api-id"
      - key: API_HASH
        value: "your-telethon-api-hash"

